services:
  client:
    image: node:16.20.2
    container_name: ${CLIENT_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    networks:
      - autoencoder-net
networks:
  autoencoder-net:
    driver: autoencoder-net
    name: autoencoder-net
    external: true