FROM ubuntu:20.04
WORKDIR /workspace

RUN apt update
RUN apt install python3 python3-pip -y
COPY requirements.api.txt requirements.txt
RUN pip install --disable-pip-version-check -r requirements.txt

COPY . .
CMD ["/bin/bash", "./scripts/run_api.sh"]
