FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-devel
WORKDIR /workspace

RUN apt update
RUN apt install python3 python3-pip -y
RUN apt install -y git
COPY requirements.api.txt requirements.txt
RUN pip install --disable-pip-version-check -r requirements.txt

COPY . .
CMD ["/bin/bash", "./scripts/run_api.sh"]
